from merging_methods.merger import Merger
from merging_methods.task_arithmetic import TaskArithmetic
from merging_methods.TIES import TIES
from merging_methods.DARE import DARE
from merging_methods.localize_and_stitch import LocalizeAndStitch
from merging_methods.consensus import Consensus
from merging_methods.regmean import RegMean
from merging_methods.regmean_plusplus import RegMeanPlusPlus